
DROP DATABASE IF EXISTS SISEVID;
CREATE DATABASE SISEVID;
USE SISEVID;

--  CREACION DE LAS TABLAS   ------------------------------------------------------------------------------------------

CREATE TABLE LUGAR_GEOGRAFICO(
	ID_LUGAR_GEOGRAFICO BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(100) NOT NULL,
    PARALELO VARCHAR(20) NULL,
    MERIDIANO VARCHAR(20) NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 

CREATE TABLE EVIDENCIA(
	ID_EVIDENCIA BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(50) NULL,
    DESCRIPCIÓN VARCHAR(500) NULL,
    TIPO VARCHAR(50) NULL,
    TIPO_ARCHIVO VARCHAR(50) NULL,
    FECHA_CREACION_EVIDENCIA DATE NULL,
    FECHA_REGISTRO_EVIDENCIA DATE NULL,
    AUTORES VARCHAR(50) NULL,
    OBSERVACION VARCHAR(500) NULL,
	ID_LUGAR_GEOGRAFICO BIGINT(20) NULL,
    ESTADO VARCHAR(30) NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
);
ALTER TABLE EVIDENCIA ADD CONSTRAINT FK_EVIDENCIA_FK1 FOREIGN KEY (ID_LUGAR_GEOGRAFICO)
      REFERENCES LUGAR_GEOGRAFICO (ID_LUGAR_GEOGRAFICO) ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE EVIDENCIA_DETALLE(
	ID_EVIDENCIA_DETALLE BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_EVIDENCIA BIGINT(20) NOT NULL,
    USUARIO_MODIFICACION VARCHAR(20) NOT NULL,
    FECHA_MODIFICACION DATETIME NOT NULL, 
    ESTADO_ANTERIOR VARCHAR(30) NULL,
    ESTADO_ACTUAL VARCHAR(30) NULL
);
ALTER TABLE EVIDENCIA_DETALLE ADD CONSTRAINT FK_EVIDENCIA_DETALLE_FK1 FOREIGN KEY (ID_EVIDENCIA)
      REFERENCES EVIDENCIA (ID_EVIDENCIA) ON DELETE RESTRICT ON UPDATE RESTRICT;
 
 
CREATE TABLE TITULO(
	ID_TITULO BIGINT(20) AUTO_INCREMENT PRIMARY KEY,  
	DESCRIPCION VARCHAR(100) NOT NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 

CREATE TABLE CAPITULO (
	ID_CAPITULO  BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_TITULO BIGINT(20) NOT NULL,
	DESCRIPCION VARCHAR(100) NOT NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
);
ALTER TABLE CAPITULO ADD CONSTRAINT FK_CAPITULO_FK1 FOREIGN KEY (ID_TITULO)
      REFERENCES TITULO (ID_TITULO) ON DELETE RESTRICT ON UPDATE RESTRICT;

 CREATE TABLE CONDICION(
	ID_CONDICION BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_CAPITULO BIGINT(20) NOT NULL,  
	DESCRIPCION VARCHAR(100) NOT NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 
ALTER TABLE CONDICION ADD CONSTRAINT FK_CONDICION_FK1 FOREIGN KEY (ID_CAPITULO)
      REFERENCES CAPITULO (ID_CAPITULO) ON DELETE RESTRICT ON UPDATE RESTRICT;


CREATE TABLE SECCION(
	ID_SECCION BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_CAPITULO BIGINT(20) NOT NULL,  
	DESCRIPCION VARCHAR(100) NOT NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 
ALTER TABLE SECCION ADD CONSTRAINT FK_SECCION_FK1 FOREIGN KEY (ID_CAPITULO)
      REFERENCES CAPITULO (ID_CAPITULO) ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE ARTICULO(
	ID_ARTICULO BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_SECCION BIGINT(20) NOT NULL,   
	DESCRIPCION VARCHAR(100) NOT NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
);
ALTER TABLE ARTICULO ADD CONSTRAINT FK_ARTICULO_FK1 FOREIGN KEY (ID_SECCION)
      REFERENCES SECCION (ID_SECCION) ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE LITERAL(
	ID_LITERAL BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_ARTICULO BIGINT(20) NULL,
	CODIGO VARCHAR(3) NOT NULL,    
	DESCRIPCION VARCHAR(100) NOT NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 
ALTER TABLE LITERAL ADD CONSTRAINT FK_LITERAL_FK1 FOREIGN KEY (ID_ARTICULO)
      REFERENCES ARTICULO (ID_ARTICULO) ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE PARAGRAFO(
	ID_PARAGRAFO BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_CAPITULO BIGINT(20) NULL,
	CODIGO VARCHAR(3) NOT NULL,    
	DESCRIPCION VARCHAR(100) NOT NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 
ALTER TABLE PARAGRAFO ADD CONSTRAINT FK_PARAGRAFO_FK1 FOREIGN KEY (ID_CAPITULO)
      REFERENCES CAPITULO (ID_CAPITULO) ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE NUMERAL(
	ID_NUMERAL BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_LITERAL BIGINT(20) NULL,
	CODIGO VARCHAR(3) NOT NULL,    
	DESCRIPCION VARCHAR(100) NOT NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 
ALTER TABLE NUMERAL ADD CONSTRAINT FK_NUMERAL_FK1 FOREIGN KEY (ID_LITERAL)
      REFERENCES LITERAL (ID_LITERAL) ON DELETE RESTRICT ON UPDATE RESTRICT;

--  RELACIONES MUCHOS A MUCHOS     ------------------------------------------------------------------------------------------

CREATE TABLE EVIDENCIA_ARTICULO(
	ID_EVIDENCIA_ARTICULO BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_EVIDENCIA BIGINT(20) NULL,
    ID_ARTICULO BIGINT(20) NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 
ALTER TABLE EVIDENCIA_ARTICULO ADD CONSTRAINT FK_EVIDENCIA_ARTICULO_FK1 FOREIGN KEY (ID_EVIDENCIA)
      REFERENCES EVIDENCIA (ID_EVIDENCIA) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE EVIDENCIA_ARTICULO ADD CONSTRAINT FK_EVIDENCIA_ARTICULO_FK2 FOREIGN KEY (ID_ARTICULO)
      REFERENCES ARTICULO (ID_ARTICULO) ON DELETE RESTRICT ON UPDATE RESTRICT;
      
CREATE TABLE EVIDENCIA_LITERAL(
	ID_EVIDENCIA_LITERAL BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_EVIDENCIA BIGINT(20) NULL,
    ID_LITERAL BIGINT(20) NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 
ALTER TABLE EVIDENCIA_LITERAL ADD CONSTRAINT FK_EVIDENCIA_LITERAL_FK1 FOREIGN KEY (ID_EVIDENCIA)
      REFERENCES EVIDENCIA (ID_EVIDENCIA) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE EVIDENCIA_LITERAL ADD CONSTRAINT FK_EVIDENCIA_LITERAL_FK2 FOREIGN KEY (ID_LITERAL)
      REFERENCES LITERAL (ID_LITERAL) ON DELETE RESTRICT ON UPDATE RESTRICT;
      
CREATE TABLE EVIDENCIA_NUMERAL(
	ID_EVIDENCIA_NUMERAL BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_EVIDENCIA BIGINT(20) NULL,
    ID_NUMERAL BIGINT(20) NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 
ALTER TABLE EVIDENCIA_NUMERAL ADD CONSTRAINT FK_EVIDENCIA_NUMERAL_FK1 FOREIGN KEY (ID_EVIDENCIA)
      REFERENCES EVIDENCIA (ID_EVIDENCIA) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE EVIDENCIA_NUMERAL ADD CONSTRAINT FK_EVIDENCIA_NUMERAL_FK2 FOREIGN KEY (ID_NUMERAL)
      REFERENCES NUMERAL (ID_NUMERAL) ON DELETE RESTRICT ON UPDATE RESTRICT;
      
CREATE TABLE EVIDENCIA_PARAGRAFO(
	ID_EVIDENCIA_PARAGRAFO BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_EVIDENCIA BIGINT(20) NULL,
    ID_PARAGRAFO BIGINT(20) NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 
ALTER TABLE EVIDENCIA_PARAGRAFO ADD CONSTRAINT FK_EVIDENCIA_PARAGRAFO_FK1 FOREIGN KEY (ID_EVIDENCIA)
      REFERENCES EVIDENCIA (ID_EVIDENCIA) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE EVIDENCIA_PARAGRAFO ADD CONSTRAINT FK_EVIDENCIA_PARAGRAFO_FK2 FOREIGN KEY (ID_PARAGRAFO)
      REFERENCES PARAGRAFO (ID_PARAGRAFO) ON DELETE RESTRICT ON UPDATE RESTRICT;
      
--     USUARIOS -----------------------------------

CREATE TABLE USUARIO_INFO_CONTACTO(
	ID_USUARIO_INFO_CONTACTO BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    TIPO_DOCUMENTO VARCHAR(100) NOT NULL,
    NUMERO_DOCUMENTO VARCHAR(100) NOT NULL,
    NOMBRES VARCHAR(100) NOT NULL,    
	APELLIDOS VARCHAR(100) NOT NULL,
    NUMERO_CONTACTO VARCHAR(10) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 

CREATE TABLE USUARIO_ROLES(
	ID_USUARIO_ROLES BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
	DESCRIPCION VARCHAR(100) NOT NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 

CREATE TABLE USUARIO(
	ID_USUARIO BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO_INFO_CONTACTO BIGINT(20) NOT NULL,
    ID_USUARIO_ROLES BIGINT(20) NOT NULL,
    USUARIO VARCHAR(10) NOT NULL,    
	CONTRASEÑA VARCHAR(10) NOT NULL,
    USUARIO_CREACION VARCHAR(20) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL
); 
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_FK1 FOREIGN KEY (ID_USUARIO_INFO_CONTACTO)
      REFERENCES USUARIO_INFO_CONTACTO (ID_USUARIO_INFO_CONTACTO) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_FK2 FOREIGN KEY (ID_USUARIO_ROLES)
      REFERENCES USUARIO_ROLES (ID_USUARIO_ROLES) ON DELETE RESTRICT ON UPDATE RESTRICT;

